# Generated by Django 5.2.3 on 2025-06-28 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_category_category_name_en_category_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_store.category'),
            preserve_default=False,
        ),
    ]
